bases:
  - ../base

patchesJson6902:
- target:
    group: tekton.dev
    version: v1alpha1
    kind: EventListener
    name: cicd-event-listener
  path: eventlistener_patch.yaml
  # path: ../overlays/eventlistener_patch.yaml # fix problem here